### ISSUE TITLE
Manual upload not possible because 'parent_widget' missing

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#17]
Windows 10 version 2004
DCOR-Aid 0.5.8

DCOR-Aid was set up in "playground" mode to get to know the software. When pressing "New manual upload" in the "Uploads" tab, an unhandled exception occurs:

![DCOR_Aid_0-5-8_manual_upload_not_working](https://user-images.githubusercontent.com/75362246/127106741-f5043c1f-5910-4c08-8fbe-ffe07526a415.PNG)

**Comment by B-Hartmann** [comment]
This also happens when I switch to the user scenario "DCOR" and login with my user credentials.

**Comment by paulmueller** [comment]
Thanks!
