### ISSUE TITLE
Adding datasets to a collection in a convenient way

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#29]
It looks like I can only add a dataset to a collection by browsing to that dataset, then clicking on "Collections", search for the collection I want to add it to, and click "Add to collection".
It would be convenient to open a collection and have a button there saying "Add dataset", and then I can search for datasets or maybe get the option to choose from a circle.
Something like selecting multiple datasets via check boxes and then clicking "Add to collection" would be nice.

**Comment by paulmueller** [comment]
I transferred this to DCOR-Aid, since it would be too much work to implement this in CKAN/DCOR. See also #11.

**Comment by paulmueller** [comment]
Duplicate of #11
