### ISSUE TITLE
Option to download complete dataset

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#30]
Is there an option to download all files of a dataset together, for example as a zip file?
If I knew I was going to a place without internet or slow internet and wanted to save some datasets for offline analysis on my PC, it would be nice to have the option to download everything together instead of clicking everytime for each single file on "Explore -> Download".

**Comment by paulmueller** [comment]
This is going to be implemented in DCOR-Aid (see #1).

**Comment by paulmueller** [comment]
Fixed alongside #13
