### ISSUE TITLE
DCOR-Aid does not start

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#41]
The latest version of DCOR-Aid was downloaded and installed, but after starting it, it gets stuck and tries to display an error message, but it's just a white window.

Windows 10 version 1909
DCOR-Aid 0.7.7

![Dcoraid_error](https://user-images.githubusercontent.com/75362246/140905663-7a4173be-b109-41d2-8e30-8148e645ff53.JPG)

Is there any other way (log files etc.) how to get the actual error message?

**Comment by paulmueller** [comment]
Do you have Python on that machine? Could you try `pip install dcoraid` and `python -m dcoraid` (maybe the error message does not show because it's a frozen application).

Alternatively, could you please download this dev version here (build still running): https://ci.appveyor.com/project/paulmueller/dcor-aid/builds/41460366/artifacts and drag-and-drop the installed executable in a command line and run it?

**Comment by B-Hartmann** [comment]
Python 3.8.5 is installed via Anaconda.

I installed dcoraid with pip as suggested and run `python -m dcoraid` in the Anaconda prompt, I got the following result:  
no DCOR-Aid window opened and in the terminal, there were the following error messages:  
QWindowsContext::windowsProc: No Qt Window found for event 0x83 (WM_NCCALCSIZE), hwnd=0x0x602ce.
QWindowsContext::windowsProc: No Qt Window found for event 0x5 (WM_SIZE), hwnd=0x0x602ce.
QWindowsContext::windowsProc: No Qt Window found for event 0x3 (WM_MOVE), hwnd=0x0x602ce.

**Comment by paulmueller** [comment]
Please try `pip uninstall pyqt5` and `conda install pyqt5`.
What about the alternative dev version?

**Comment by paulmueller** [comment]
I just implemented logging (#18). With this development version: https://ci.appveyor.com/project/paulmueller/dcor-aid/builds/41466296/artifacts you should be able to see the error message in the logs. The logs should be located in directories named like:

```
"C:/Users/<USER>/AppData/Local/<APPNAME>",
"C:/ProgramData/<APPNAME>", "<APPDIR>", "<APPDIR>/data"
"<APPDIR>/data/<APPNAME>"
```

**Comment by paulmueller** [comment]
OK, it seems like the API-Key is not set. Actually this should not be a problem, so I wonder what is going on.
Maybe I fixed it with these changes. Could you please try this development version?
https://ci.appveyor.com/project/paulmueller/dcor-aid/builds/41482839/artifacts

**Comment by B-Hartmann** [comment]
It works!  
Seems that there are no problems with version 0.7.8.post4
