### ISSUE TITLE
enh: Let user choose download location

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#43]
It would be nice if I could choose the location where DCOR-Aid will save the downloaded resources myself.

I could even image a checkbox in the settings like in Firefox that says "Always ask where to save downloads".

But since the motivation of DCOR is to have the datasets online and access them via the internet to save local resources, this has low priority and implementation could be decided on further user experience.

**Comment by paulmueller** [comment]
Keep track of previous download locations to be able to skip downloads (don't skip sha256 check).
