### ISSUE TITLE
Display path to datasets in Upload-tab

### ISSUE THREAD

**Issue by maxschloegel** [DCOR-dev/DCOR-Aid#56]
As a data analyst, I need to be able to trace back uploading datasets to their current directory.
Often, when an upload fails, it is necessary to infer the original dataset on the local machine that was supposed to be uploaded.(For example could one then sort the error-throwing datasets out and remove already uploaded datasets to get a better overview and a cleaner data storage).

Currently my approach is to go through all datasets I am uploading and cross-checking with the 'raiXYZ..' by iterating over all 'uker.dcoraid-task' files and returning the corresponding folder.

If I would be able to see the original file path of an uploading file, this would make the backtracing much easier.

For the implementation, adding a column in the 'Uploads'-tab with header 'Path' would be sufficient.

**Comment by paulmueller** [comment]
The problem is that a dataset can contain multiple files. So a single column would not be enough. But I think an action button with a question mark "?" that displays information about the current upload might help. Maybe even a separate side panel dedicated to that (upon row selection).

What do you think?

**Comment by B-Hartmann** [comment]
That would be useful! Once you loaded the task file, you can just see the name of the dataset. If you work with many datasets as part of a bigger project, you don't always have that specific and detailed names, so an option, like you suggested, that would allow you to see more information about an upload would really help to check what data you are uploading (or have uploaded already, in case you have finished jobs that are still in the list).

**Comment by maxschloegel** [comment]
Thanks Paul for taking the time!
Good point about the multiple files, did not take that into consideration. I feel like a separate side panel would be great, and probably a bit more comfortable than the '?' button, but both are great solutions.

**Comment by paulmueller** [comment]
I added this functionality, however please note that if the input data is compressed, the paths displayed will point to the compressed files in the cache. But I hope this makes everything more transparent and usable anyway.
