### ISSUE TITLE
Data upload problem on macOS Catalina

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#58]
macOS 10.15.7 (Catalina)
DCOR-Aid 0.8.6

There seems to be a connection to DCOR, and a "new manual upload" can be started, but the status of the upload job gets stuck during "init". Restart of the software and the Mac didn't help. The drafts are created, this can be seen when logging in to the website.

**Comment by paulmueller** [comment]
Is there anything tin the DCOR-Aid logs (sorry, I have not implemented a log viewer, so you have to search for it in the user's home directory)? Did you try the latest version (0.11.0)?

**Comment by B-Hartmann** [comment]
The collaborator has sent me the following files:

![error_message_DCOR-Aid_censored](https://user-images.githubusercontent.com/75362246/160547377-32e0da9e-1a2b-4919-9b7d-525717bd3b67.png)
[dcoraid_2022-03-21_16-51-50.log](https://github.com/DCOR-dev/DCOR-Aid/files/8368633/dcoraid_2022-03-21_16-51-50.log)
[dcoraid_2022-03-21_15-40-08.log](https://github.com/DCOR-dev/DCOR-Aid/files/8368634/dcoraid_2022-03-21_15-40-08.log)

**Comment by paulmueller** [comment]
Updating DCOR-Aid should resolve this.

**Comment by paulmueller** [comment]
Please reopen if the problem persists.
