### ISSUE TITLE
Make sure self-signed SSL certificates of DCOR-med instances are used everywhere

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#61]
DCOR-Aid 0.11.1 (health facility scenario)
Windows 10

The download process of a single file does not finish, the status is error but there is no button to get the actual error message:
![Screenshot_1_annotated](https://user-images.githubusercontent.com/75362246/164712849-6d068302-a824-4488-ab6a-4e097f2aa432.png)

The download location was changed in the preferences and confirmed by pressing "apply". Read/write access to the download location is no problem, copying manually a Word file there and deleting it was no problem.
When clicking on the eye symbol, the website of the DCOR instance opens. When clicking on the folder icon, the correct download location opens and there is actually a folder with the correct dataset name, but the folder is empty. Clicking on the trashcan symbol aborts/deletes the download job.

Could it be that the error message was not handled correctly, so that "error" is shown as status, but not the error icon under "actions"?

**Comment by paulmueller** [comment]
Is there anything in the logs?

**Comment by paulmueller** [comment]
As suspected, the issue is the self-signed SSL certificate.
