### ISSUE TITLE
Speed up CLI with simultaneous uploads and compression?

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#67]
The DCOR-Aid app has several threads that take care of uploading, compressing, verifying data etc. In the cli, the whole process is linear for one dataset at a time, which means that when uploading one dataset and waiting for the DCOR server to process the file, nothing happens. In the GUI app, dcoraid would already start compressing the next dataset, which significantly speeds up the overall processing time.

Is that available in the CLI as well? If not, does it make sense to have that? Is it even feasible? Or not, because the output to the cmd would be very messy?

**Comment by paulmueller** [comment]
It does not really make sense for the CLI. But you could use MPL-Data-cast or dclab-compress to compress datasets before attempting the upload. dcoraid will by design only compress datasets if they are not already compressed.
